services:
  ui:
    container_name: profile-ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    entrypoint: ["/opt/scripts/build_ui.sh"]
    working_dir: /opt/ui
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - type: bind
        source: ./ui
        target: /opt/ui
      - type: bind
        source: ./scripts
        target: /opt/scripts
